### ISSUE TITLE
User journary

### ISSUE THREAD

**Issue by zhouqiang-cl** [reddio-com/unity-sdk-demo#1]
1. release can not download https://github.com/reddio-com/reddio-sdk/releases 
2. Did we need install unity walletConncect?
3. How to connect to goerli?

**Comment by STRRL** [comment]
> release can not download https://github.com/reddio-com/reddio-sdk/releases

I think we could make this repo public to download the release artifacts.

Or we could create another repo, and only use it for releasing artifacts.

What do you think? @zhouqiang-cl 

> Did we need install unity walletConncect?

Yes.

In this demo repo, the dependency library "Wallet Connect" has been already imported: https://github.com/reddio-com/unity-sdk-demo/tree/main/Assets/WalletConnectUnity, 

> How to connect to goerli?

It should configure **both** WalletConnect (in unity) and MetaMask(the android app) to use the goerli network.

I just notice that the demo does not setup goerli network by default: https://github.com/reddio-com/unity-sdk-demo/issues/2

I think we should build documentation for https://github.com/reddio-com/reddio-sdk, and introduce how to use it. Where should I put the docs?

**Comment by STRRL** [comment]
> > Did we need install unity walletConncect?
> 
> Yes.
> 
> In this demo repo, the dependency library "Wallet Connect" has been already imported: https://github.com/reddio-com/unity-sdk-demo/tree/main/Assets/WalletConnectUnity,

The think in the readme has been updated: https://github.com/reddio-com/unity-sdk-demo#step-3-integrate-with-metamask

**Comment by neilydhan** [comment]
close it as no more questions
